dev_mode = false
multinode_mode = true
replication_enable = true # make true for production
is_local = false          # make false for production
max_size = 100
fee_limit = 100000
rate_limit = 15
time_frame_seconds = 100
expiration_seconds = 100
block_time = 10000

# Node 1
node_port = "5010"
node_ip_address = "/ip4/0.0.0.0/tcp/5010"
node_private_key = "8cbdda58eddddd61fd45bf1904f4525092d4b7bebba5471eedd364d31b8fb05f"
node_verifying_key = "023d51dc03e4dca1cfa1a7e543de3602b5213062c0600b53ef783849c6b7f4878d"
node_address = "19051a4ed48faef8feca59c287fa2650d2f525e2"
node_metadata = "metadata"
cluster_address = "0101010101010101010101010101010101010101"
boot_nodes = [
    "/ip4/3.36.91.184/tcp/5010/p2p/16Uiu2HAm5cnMkuwwmNyNdHNzxvhtHxKQ1xJtF7zb5Fpm9zbe7qmm",
]
sync_node_address = "http://3.36.91.184:50052"
grpc_port = "0.0.0.0:50052"
jsonrpc_port = "0.0.0.0:50051"
db_type = 1
validator_pool_address = "522b3294fe78d57a1d7e1c37393f11841f6a9494"
cassandra_host = "127.0.0.1:9045"
cassandra_username = "cassandra"
cassandra_password = "cassandra"
cassandra_keyspace = "cipher"
postgres_host = "postgres1:5432"
postgres_username = "postgres"
postgres_password = "postgres"
postgres_db_name = "cipher"
postgres_pool_size = 10
rocksdb_name = "cipher_rocks"
