[workspace]
resolver = "2"

members = [
    "account",
    "block",
    "block_proposer",
    "cli",
    "cluster",
    "consensus",
    "contract",
    "contract_instance",
    "contract_instance_manager",
    "db",
    "execute",
    "event",
    "evm_helper",
    "vrf-helper",
    "mempool",
    "node",
    "p2p",
    "primitives",
    "server",
    "staking",
    "sub_cluster",
    "system",
    "validator",
    "node_info",
    "vote",
    "vote_result",
    "validate",
    "util",
    "genesis",
    "db_traits",
    "evm_interpreter",
    "evm_precompile", 
    "types",
    #"relayer_solana",
    "relayer_bitcoin",
    "relayer_ethereum", "zk_rollups", "optimistic_rollups",
    "cipher-rpc", "merkle",
]
