[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
clap = { version = "4.4.8", features = ["derive"] }
itertools = "0.12.0"
jsonrpsee = { version = "0.21.0", features = [
    "server",
    "ws-client",
    "macros",
    "client-ws-transport-native-tls",
] }
jsonrpsee-server = "0.21.0"
hex = "0.4.3"
hyper = "1.1.0"
cipher-rpc = { package = "cipher-rpc", path = '../cipher-rpc', default-features = false }
sha3="*"
lazy_static = "1.4.0"
libp2p = { version = "0.51.4", features = ["secp256k1"] }
log = "0.4.18"
pretty_env_logger = "0.5.0"
primitive-types = { version = "0.12", default-features = false }
prost = "0.12.2"
prost-types = "0.12.2"
secp256k1 = { version = "0.27.0", no-default = true, features = ["recovery"] }
libsecp256k1 = "0.7.1"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full"] }
tonic = "0.10.2"
tonic-web = "0.10.2"
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.5.1", features = ["full"] }
tokio-stream = "0.1.14"
futures-core = "0.3.29"
ethers = { version = "2.0.11", features = ["ws", "rustls"] }
alloy-primitives = "0.6.0"
alloy-dyn-abi = "0.6.0"
rlp = "0.5.2"
dotenvy = "0.15.7"
fc-rpc-core = "1.0.0"
async-scoped = { version = "0.8.0", features = ["use-tokio"] }
ethereum-types = "0.14.1"


account = { package = 'account', path = '../account', default-features = false }
db = { package = 'db', path = '../db', default-features = false }
block = { package = 'block', path = '../block', default-features = false }
contract = { package = 'contract', path = '../contract', default-features = false }
contract-instance = { package = 'contract_instance', path = '../contract_instance', default-features = false }
event = { package = 'event', path = '../event', default-features = false }
execute = { package = 'execute', path = '../execute', default-features = false }
vrf-helper = { package = 'vrf-helper', path = '../vrf-helper', default-features = false }
node_crate = { package = 'node', path = '../node', default-features = false }
system = { package = 'system', path = '../system', default-features = false }
primitives = { package = 'primitives', path = '../primitives', default-features = false }
genesis = { package = 'genesis', path = '../genesis', default-features = false }
staking = { package = 'staking', path = '../staking', default-features = false }
validator = { package = 'validator', path = '../validator', default-features = false }
types = { package = 'types', path = '../types', default-features = false }
node-info = { package = 'node_info', path = '../node_info', default-features = false }
util = { package = 'util', path = '../util', default-features = false }
ethereum = { version = "0.15.0", default-features = false, features = [
    "with-serde",
] }
ethabi = "18.0.0"
structopt = "0.3.26"
directories = "5.0.1"
toml = "0.8.8"
evm-runtime = "0.41.0"


[dev-dependencies]
mockall = "0.12.1"

[[bin]]
name = "server"
path = "src/main.rs"