[package]
name = "genesis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitives = { package = 'primitives', path = '../primitives', default-features = false }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
secp256k1 = { version = "0.27.0"}
anyhow = "1.0.71"
async-trait = "0.1.68"
rand = "0.8.5"
tiny-bip39 = "1.0.0"
directories = "5.0.1"
hex = "0.4.3"

# System Dependencies
db = { package = 'db', path = '../db', default-features = false }
vrf-helper = { package = 'vrf-helper', path = '../vrf-helper', default-features = false }
system = { package = 'system', path = '../system', default-features = false }
block_proposer = { package = 'block_proposer', path = '../block_proposer', default-features = false }