[package]
name = "db_traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1"
primitives = { package = 'primitives', path = '../primitives', default-features = false }
system = { package = 'system', path = '../system', default-features = false }
cipher-rpc = { package = "cipher-rpc", path = '../cipher-rpc', default-features = false }
ethers = { version = "2.0.8", features = ["ws", "rustls"] }
types = { package = 'types', path = '../types', default-features = false }